jobs:
- name: main
  plan:
  - get: concourse-example
  - task: concourse-example
    file: concourse-example/task.yml
  - get: redis-server

resources:
- name: concourse-example
  type: git
  source:
    uri: https://github.com/kdolor-pivotal/concourse-example.git
    branch: master
- name: redis-server
  type: docker-image
  source:
    repository: kdolor/redis-server