jobs:
- name: main
  plan:
  - get: concourse-example
  - task: unit
    file: ./task.yml

resources:
- name: concourse-example
  type: git
  source:
    uri: https://github.com/kdolor-pivotal/concourse-example.git
    branch: master